### ISSUE TITLE
uf2 crate name

### ISSUE THREAD

**Issue by jacobrosenthal** [sajattack/uf2conv-rs#2]
Damn, you got the uf2 crate name on me.

so my uf2 has a binary and a library. 
https://github.com/jacobrosenthal/uf2-rs

My binary does flashing, verify, etc. I think convert would work well as a subcommand there as well so Im hoping to bring your lib in there. But I also think I think theres a good reason to have your converter not depend on my usb dependencies so I think it should be available separate as it is now.

it would be good to actually make a cargo-conv type crate that can do uf2 and dfu conversions, like cargo conv --examples ferris_img --release -o ./Volumes/Pygamer/ferris_img.uf2 or something

Can you think of a name I should use, or would you be willing to give up uf2? and take like uf2-conv?

**Comment by sajattack** [comment]
Yeah I guess your crate is more general purpose. I'll yield.

**Comment by jacobrosenthal** [comment]
Update. I ended up going with hf2, since the hid part doesnt have anything uf2 about it, and it technically has the name hf2
