### ISSUE TITLE
help understanding relationship between memory.x and base offset

### ISSUE THREAD

**Issue by TheButlah** [sajattack/uf2conv-rs#6]
Hi, I was told that for my particular bootloader, I should set -b to 0x26000, which accounts for the adafruit bootloader + the proprietary Bluetooth stack that the nrf52840 uses.

Should I set memory.x to 0x26000? What exactly is the relationship between memory.x and the base offset?

**Comment by jacobrosenthal** [comment]
Yeah the base is what flash address the tool writes your image to. The flash origin of the memory.x is the base offset. So if your chips flash memory starts at 0x0 like nordics do, its 0x0.

Complications occur when you have a softdevice or a bootloader or something which is placed at 0x0 and you cant overwrite, so you have to avoid it. which is a bit out of scope of this tool.

You can google something like "nordic softdevice app ram base address" and see tutorials and images of different softdevices  (plus the mbr) and how much space they require. 

But assuming you have a working rust app,  whatever address you or whoever calculated your memory.x flash origin to, thats what you use.

**Comment by jacobrosenthal** [comment]
Btw we all hang out in https://matrix.to/#/#rust-embedded:matrix.org
